### ISSUE TITLE
自定义sql获取指标失败

### ISSUE THREAD

**Issue by shardingbh** [gaoyuan98/dameng_exporter#11]
配置文件内容如下：
[[metric]]
context = "table_metrics"
labels = [ "name" ]
request = "SELECT SQL_text as name,exec_time as long_query_time FROM V$LONG_EXEC_SQLS ORDER BY exec_time DESC LIMIT 10"
metricsdesc = { long_query_time = "慢SQL执行时间" }
metricstype = { long_query_time = "gauge" }

[[metric]]
context = "table_metrics"
labels = [ "name" ]
request = "SELECT lc.table_id AS name, vs.sql_text AS blocked_sql FROM  v$lock lc LEFT JOIN v$trxwait vtw ON (lc.trx_id = vtw.id) LEFT JOIN   v$trx vt ON (vtw.id = vt.id) LEFT JOIN  v$sessions vs ON (vt.sess_id = vs.sess_id) WHERE vs.sql_text IS NOT NULL"
metricsdesc = { blocked_sql = "阻塞的sql" }
metricstype = { blocked_sql = "gauge" }

阻塞的sql指标无法出来，报错如下：
![image](https://github.com/user-attachments/assets/52bb17ee-729b-4a1d-9e38-409033f1dc2e)

请问是什么原因导致的？

**Comment by gaoyuan98** [comment]
在dameng_exporter.config配置文件里加上这句registerHostMetrics=false。关闭掉AP进程的检查。现在默认会检测机器上的进程，报错看应该是处理不完善。可以先关掉
![image](https://github.com/user-attachments/assets/c310f116-71d6-4837-affe-8eddae833090)

**Comment by shardingbh** [comment]
你好，加上这句registerHostMetrics=false。 只是不报错了，但是对应指标还是未出来。还有其它解决方案吗？

**Comment by gaoyuan98** [comment]
注意一下几点
1）如果SQL查询没有值的话，指标是不显示的
2）最低需要使用v1.0.7版本
3）自定义SQL里面每个metric的context内容不可与其他指标一致，否则会出现指标冲突
4）提供一个示例
![image](https://github.com/user-attachments/assets/6dd48994-59be-43c4-87b1-d8687ceee5fb)
![image](https://github.com/user-attachments/assets/9334ded1-fd09-4011-9a7f-5d0a3a579044)

**Comment by shardingbh** [comment]
ok了，感谢支持！
