### ISSUE TITLE
custom_collector收集自定义sql指标提示重复收集

### ISSUE THREAD

**Issue by liuzm7188** [gaoyuan98/dameng_exporter#2]
custom_collector收集自定义sql指标提示重复收集，sql查询有多条数据时，会报错，如果只有一条数据是正常的
custom_metrics.toml如下：
![image](https://github.com/user-attachments/assets/d359792c-e715-40b0-a687-2405f9a39e5d)

SQL结果：
行号     name           SPACE
---------- -------------- -----
1          SYSTEM         74
2          ROLL           640
3          TEMP           138
4          MAIN           11136
5          PROMETHEUS.DBF 512

报错如下：
![image](https://github.com/user-attachments/assets/c42c62a8-4acb-4089-ace9-ea87ea546b5c)

**Comment by gaoyuan98** [comment]
最新的版本v1.0.4已支持
![image](https://github.com/user-attachments/assets/b8b3646a-9386-4493-83a1-61c36a468a45)
