### ISSUE TITLE
达梦8 window版本运行报错

### ISSUE THREAD

**Issue by simyoung** [gaoyuan98/dameng_exporter#3]
大佬你好，请问window版本的运行报如下错误是什么原因？
2024-09-18 11:24:07     DEBUG   collector/db_license_info_collector.go:47       func exec time：404ms
2024-09-18 11:24:07     ERROR   collector/collector.go:155      Error querying database{error 26 0  Error -2103: 第14 行附近出现错误:
无效的模式名[SYSJOB]
stack info:
   1).  github.com/gaoyuan98/dm.(*dm_build_758).dm_build_791
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zq.go:723
   2).  github.com/gaoyuan98/dm.(*dm_build_758).dm_build_747
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zq.go:710
   3).  github.com/gaoyuan98/dm.(*dm_build_758).dm_build_750
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zq.go:764
   4).  github.com/gaoyuan98/dm.(*dm_build_336).dm_build_379
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/a.go:275
   5).  github.com/gaoyuan98/dm.(*dm_build_336).Dm_build_407
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/a.go:366
   6).  github.com/gaoyuan98/dm.(*dm_build_336).Dm_build_425
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/a.go:387
   7).  github.com/gaoyuan98/dm.(*DmConnection).executeInner
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/m.go:200
   8).  github.com/gaoyuan98/dm.(*DmConnection).queryContext
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/m.go:656
   9).  github.com/gaoyuan98/dm.(*filterChain).DmConnectionQueryContext
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zd.go:169
   10).  github.com/gaoyuan98/dm.(*reconnectFilter).DmConnectionQueryContext
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zf.go:259
   11).  github.com/gaoyuan98/dm.(*filterChain).DmConnectionQueryContext
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/zd.go:166
   12).  github.com/gaoyuan98/dm.(*DmConnection).QueryContext
        D:/Program Files/Go/gopath/pkg/mod/github.com/gaoyuan98/dm@v1.3.162/m.go:303
   13).  database/sql.ctxDriverQuery
        D:/Program Files/Go_1.21.12/src/database/sql/ctxutil.go:48
   14).  database/sql.(*DB).queryDC.func1
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1748
   15).  database/sql.withLock
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:3502
   16).  database/sql.(*DB).queryDC
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1743
   17).  database/sql.(*DB).query
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1726
   18).  database/sql.(*DB).QueryContext.func1
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1704
   19).  database/sql.(*DB).retry
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1538
   20).  database/sql.(*DB).QueryContext
        D:/Program Files/Go_1.21.12/src/database/sql/sql.go:1703
   21).  dameng_exporter/collector.(*DbJobRunningInfoCollector).Collect
        E:/go_code/dameng_exporter/collector/db_job_running_info_collector.go:55
   22).  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        D:/Program Files/Go/gopath/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:455
   23).  runtime.goexit
        D:/Program Files/Go_1.21.12/src/runtime/asm_amd64.s:1650
}
dameng_exporter/collector.handleDbQueryError
        E:/go_code/dameng_exporter/collector/collector.go:155
dameng_exporter/collector.(*DbJobRunningInfoCollector).Collect
        E:/go_code/dameng_exporter/collector/db_job_running_info_collector.go:57
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        D:/Program Files/Go/gopath/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:455

**Comment by simyoung** [comment]
使用的是1.0.4版本的exporter,dameng_exporter_v1.0.4_windows_amd64.tar.gz

**Comment by gaoyuan98** [comment]
https://github.com/gaoyuan98/dameng_exporter/issues/1   看一下这个

**Comment by simyoung** [comment]
> #1 看一下这个

多谢
