### ISSUE TITLE
已支持的指标为啥在exporter中搜索不到

### ISSUE THREAD

**Issue by heyuanchou** [gaoyuan98/dameng_exporter#5]
github主页上md文件提到：
数据库QPS数量	dmdbms_qps_count
数据库TPS数量	dmdbms_tps_count
但是我在metrics中搜索不到。。。
请问是什么原因
![dameng8](https://github.com/user-attachments/assets/097a2c7b-f518-4121-9522-4bfb14491f69)

**Comment by heyuanchou** [comment]
达梦数据库使用的是dm8_20241022_x86_rh6_64_single.tar镜像
exporter使用的是dameng_exporter:v1.0.6镜像

**Comment by gaoyuan98** [comment]
文档写错了 应该是这个指标dmdbms_statement_type_info。  
tps就是statement_name="transaction total count"
qps就是select statements以及其他的
![image](https://github.com/user-attachments/assets/4a4e9b3f-e4e4-4b5e-beef-22edf98ee18b)
