### ISSUE TITLE
修改告警级别

### ISSUE THREAD

**Issue by mayanshun** [gaoyuan98/dameng_exporter#6]
需要修改[prometheus.yml](https://github.com/gaoyuan98/dameng_exporter/blob/master/doc/protheues_%E5%91%8A%E8%AD%A6%E8%A7%84%E5%88%99/prometheus.yml)文件里面的中文告警级别为英文的

**Comment by gaoyuan98** [comment]
指的是[https://github.com/gaoyuan98/dameng_exporter/blob/master/doc/protheues_%E5%91%8A%E8%AD%A6%E8%A7%84%E5%88%99/rules/dm_alter_rules.yml](dm_alter_rules.yml) 里面的severity标签吗  比如说severity: 严重 改成severity: ERROR

**Comment by gaoyuan98** [comment]
已提供对应的rule规则文件
